### ISSUE TITLE
tool chokes on variadics

### ISSUE THREAD

**Issue by AlexanderBollbach** [pointfreeco/swift-enum-properties#5]
I was getting an error and traced it to my `Store.swift` file where (as you guys are familiar with) the `combine` function takes a variadic argument of reducers.  I simplified to the following repro:

1) cd into the SPM checkouts directory and run the command:
`swift run generate-enum-properties /Users/alexanderbollbach/Desktop/test.swift `

test.swift contents:
```
func f(a: Int...) { }
```

2) see the following in stdout:
```
Updating /Users/alexanderbollbach/Desktop/test.swiftFatal error: Error raised at top level: SwiftSyntax.TokenKind.DecodeError.unknownTokenKind("ellipsis"): file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1100.8.259.70/swift/stdlib/public/core/ErrorType.swift, line 200
```

**Comment by hisavali** [comment]
Thanks @AlexanderBollbach for raising above issue.

Observed same issue:

I installed `Generate Enum properties` using [Homebrew](https://github.com/pointfreeco/swift-enum-properties#homebrew) option

Cloned repo and navigated to episode 0070's directory
`https://github.com/pointfreeco/episode-code-samples/tree/main/0070-composable-state-management-action-pullbacks`

and did following

<img width="1467" alt="Screenshot 2020-08-31 at 00 10 38" src="https://user-images.githubusercontent.com/2108707/91671453-be271500-eb1e-11ea-991a-9351b56309af.png">

@stephencelis @mbrandonw kindly let us know if there anything obvious missing here 🤔 
Thanks

**Comment by stephencelis** [comment]
Sorry for not replying earlier! This seems to be an issue with older versions of SwiftSyntax. It might be possible to get things working on a newer version, but we haven't had a lot of time to devote to this project. Let us know if you're interested in doing so!

[swift-case-paths](https://github.com/pointfreeco/swift-case-paths) provides a lot of the functionality of this project without the requirement of code gen, so that's where we've been directing our enum-ergonomic attention.

**Comment by stephencelis** [comment]
After discussing with Brandon, we're deprecating this code generator for [Case Paths](https://github.com/pointfreeco/swift-case-paths), which should generally perform just as well and accomplish more without code gen. Thanks for reporting, though!
